import math
from typing import List

class Solution:
    def findKthSmallest(self, coins: List[int], k: int) -> int:
        n = len(coins)
        
        # Precompute LCM and sign (-1^|S|+1) for all non-empty subsets
        subsets = []
        for i in range(1, 1 << n):
            subset_lcm = 1
            count = 0
            for j in range(n):
                if (i >> j) & 1:
                    count += 1
                    subset_lcm = math.lcm(subset_lcm, coins[j])
            sign = 1 if count % 2 == 1 else -1
            subsets.append((subset_lcm, sign))
            
        def count_valid(m: int) -> int:
            """Returns total unique amounts <= m generated by coins."""
            total = 0
            for lcm_val, sign in subsets:
                total += sign * (m // lcm_val)
            return total

        # Binary search range for the answer
        left = min(coins)
        right = min(coins) * k
        ans = right

        while left <= right:
            mid = (left + right) // 2
            if count_valid(mid) >= k:
                ans = mid
                right = mid - 1
            else:
                left = mid + 1

        return ans
        